# Generated by Django 4.1.5 on 2023-01-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_bid_auction_alter_auction_accepted_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="auction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="mainapp.auction",
            ),
        ),
    ]
